# Generates amalgamated Zydis.c / Zydis.h from an upstream source tree.
# Mirrors upstream assets/amalgamate.py (Zydis MIT).

param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRoot,

    [Parameter(Mandatory = $true)]
    [string]$OutputDir
)

$ErrorActionPreference = 'Stop'

$publicIncludePaths = @(
    (Join-Path $SourceRoot 'include'),
    (Join-Path $SourceRoot 'dependencies\zycore\include')
)
$internalIncludePaths = @(
    (Join-Path $SourceRoot 'src')
)
$includePattern = [regex]'^#\s*include\s*<((?:Zy|Generated).*)>\s*$'
$fileHeader = @(
    '// DO NOT EDIT. This file is auto-generated by `amalgamate.py`.',
    ''
)

function Find-IncludePath {
    param([string]$Include, [string[]]$SearchPaths)
    foreach ($searchPath in $SearchPaths) {
        $path = Join-Path $searchPath $Include
        if (Test-Path $path) { return (Resolve-Path $path).Path }
    }
    throw "can't find header: $Include"
}

function Merge-Headers {
    param(
        [string]$Header,
        [string[]]$SearchPaths,
        [System.Collections.Generic.HashSet[string]]$CoveredHeaders,
        [string[]]$Stack
    )

    $path = Find-IncludePath -Include $Header -SearchPaths $SearchPaths
    if ($CoveredHeaders.Contains($Header)) { return @() }
    [void]$CoveredHeaders.Add($Header)

    Write-Host "Processing header `"$Header`""
    $lines = Get-Content -Path $path

    $includeStack = @()
    if ($Stack.Count -gt 0) {
        $includeStack = @('//', '// Include stack:', ($Stack | ForEach-Object { "//   - $_" }))
    }

    $filtered = [System.Collections.Generic.List[string]]::new()
    $filtered.Add('')
    $filtered.Add('//')
    $filtered.Add("// Header: $Header")
    foreach ($stackLine in $includeStack) { $filtered.Add($stackLine) }
    $filtered.Add('//')
    $filtered.Add('')

    foreach ($line in $lines) {
        $match = $includePattern.Match($line)
        if (-not $match.Success) {
            $filtered.Add($line)
            continue
        }

        foreach ($merged in (Merge-Headers `
                -Header $match.Groups[1].Value `
                -SearchPaths $SearchPaths `
                -CoveredHeaders $CoveredHeaders `
                -Stack ($Stack + $Header))) {
            $filtered.Add($merged)
        }
    }

    return $filtered.ToArray()
}

function Merge-Sources {
    param(
        [string]$SourceDir,
        [System.Collections.Generic.HashSet[string]]$CoveredHeaders
    )

    $output = @(
        '#include <Zydis.h>',
        ''
    )

    $sourceFiles = Get-ChildItem -Path $SourceDir -Filter '*.c' -File |
        Sort-Object Name

    foreach ($sourceFile in $sourceFiles) {
        Write-Host "Processing source file `"$($sourceFile.FullName)`""
        $output += @(
            '',
            '//',
            "// Source file: $($sourceFile.Name)",
            '//',
            ''
        )

        $lines = Get-Content -Path $sourceFile.FullName
        foreach ($line in $lines) {
            $match = $includePattern.Match($line)
            if (-not $match.Success) {
                $output += $line
                continue
            }

            $include = $match.Groups[1].Value
            if ($CoveredHeaders.Contains($include)) { continue }

            if ($include -notmatch 'Internal|Generated') {
                Write-Warning "Public-looking include during source merge: $include"
            }

            Write-Host "Processing internal header `"$include`""
            $output += Merge-Headers `
                -Header $include `
                -SearchPaths ($publicIncludePaths + $internalIncludePaths) `
                -CoveredHeaders $CoveredHeaders `
                -Stack @()
        }
    }

    return $output
}

if (Test-Path $OutputDir) {
    Write-Host "Output directory exists. Deleting."
    Remove-Item -Recurse -Force $OutputDir
}
New-Item -ItemType Directory -Path $OutputDir | Out-Null

$coveredHeaders = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)

$headerLines = $fileHeader + (Merge-Headers `
    -Header 'Zydis/Zydis.h' `
    -SearchPaths $publicIncludePaths `
    -CoveredHeaders $coveredHeaders `
    -Stack @())
Set-Content -Path (Join-Path $OutputDir 'Zydis.h') -Value $headerLines -Encoding utf8NoBOM

$sourceLines = $fileHeader + (Merge-Sources `
    -SourceDir (Join-Path $SourceRoot 'src') `
    -CoveredHeaders $coveredHeaders)
Set-Content -Path (Join-Path $OutputDir 'Zydis.c') -Value $sourceLines -Encoding utf8NoBOM

Write-Host "Wrote $(Join-Path $OutputDir 'Zydis.h') and $(Join-Path $OutputDir 'Zydis.c')"